/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AsciiGalleryRouteImport } from './routes/ascii-gallery'
import { Route as CongregationRouteImport } from './routes/congregation'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoreRouteImport } from './routes/lore'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as TerminalRouteImport } from './routes/terminal'
import { Route as TransmissionsRouteImport } from './routes/transmissions'
import { Route as TransmissionsIndexRouteImport } from './routes/transmissions.index'
import { Route as TransmissionsIdRouteImport } from './routes/transmissions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AsciiGalleryRoute = AsciiGalleryRouteImport.update({
  id: '/ascii-gallery',
  path: '/ascii-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CongregationRoute = CongregationRouteImport.update({
  id: '/congregation',
  path: '/congregation',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreRoute = LoreRouteImport.update({
  id: '/lore',
  path: '/lore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalRoute = TerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionsRoute = TransmissionsRouteImport.update({
  id: '/transmissions',
  path: '/transmissions',
  getParentRoute: () => rootRouteImport,
} as any)
const TransmissionsIndexRoute = TransmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransmissionsRoute,
} as any)
const TransmissionsIdRoute = TransmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransmissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/ascii-gallery': typeof AsciiGalleryRoute
  '/congregation': typeof CongregationRoute
  '/jobs': typeof JobsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/lore': typeof LoreRoute
  '/protocol': typeof ProtocolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/stocks': typeof StocksRoute
  '/terminal': typeof TerminalRoute
  '/transmissions': typeof TransmissionsRouteWithChildren
  '/transmissions/$id': typeof TransmissionsIdRoute
  '/transmissions/': typeof TransmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/ascii-gallery': typeof AsciiGalleryRoute
  '/congregation': typeof CongregationRoute
  '/jobs': typeof JobsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/lore': typeof LoreRoute
  '/protocol': typeof ProtocolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/stocks': typeof StocksRoute
  '/terminal': typeof TerminalRoute
  '/transmissions/$id': typeof TransmissionsIdRoute
  '/transmissions': typeof TransmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/ascii-gallery': typeof AsciiGalleryRoute
  '/congregation': typeof CongregationRoute
  '/jobs': typeof JobsRoute
  '/ledger': typeof LedgerRoute
  '/library': typeof LibraryRoute
  '/lore': typeof LoreRoute
  '/protocol': typeof ProtocolRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staking': typeof StakingRoute
  '/stocks': typeof StocksRoute
  '/terminal': typeof TerminalRoute
  '/transmissions': typeof TransmissionsRouteWithChildren
  '/transmissions/$id': typeof TransmissionsIdRoute
  '/transmissions/': typeof TransmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/ascii-gallery'
    | '/congregation'
    | '/jobs'
    | '/ledger'
    | '/library'
    | '/lore'
    | '/protocol'
    | '/sitemap.xml'
    | '/staking'
    | '/stocks'
    | '/terminal'
    | '/transmissions'
    | '/transmissions/$id'
    | '/transmissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/ascii-gallery'
    | '/congregation'
    | '/jobs'
    | '/ledger'
    | '/library'
    | '/lore'
    | '/protocol'
    | '/sitemap.xml'
    | '/staking'
    | '/stocks'
    | '/terminal'
    | '/transmissions/$id'
    | '/transmissions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/ascii-gallery'
    | '/congregation'
    | '/jobs'
    | '/ledger'
    | '/library'
    | '/lore'
    | '/protocol'
    | '/sitemap.xml'
    | '/staking'
    | '/stocks'
    | '/terminal'
    | '/transmissions'
    | '/transmissions/$id'
    | '/transmissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  AsciiGalleryRoute: typeof AsciiGalleryRoute
  CongregationRoute: typeof CongregationRoute
  JobsRoute: typeof JobsRoute
  LedgerRoute: typeof LedgerRoute
  LibraryRoute: typeof LibraryRoute
  LoreRoute: typeof LoreRoute
  ProtocolRoute: typeof ProtocolRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StakingRoute: typeof StakingRoute
  StocksRoute: typeof StocksRoute
  TerminalRoute: typeof TerminalRoute
  TransmissionsRoute: typeof TransmissionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ascii-gallery': {
      id: '/ascii-gallery'
      path: '/ascii-gallery'
      fullPath: '/ascii-gallery'
      preLoaderRoute: typeof AsciiGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/congregation': {
      id: '/congregation'
      path: '/congregation'
      fullPath: '/congregation'
      preLoaderRoute: typeof CongregationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore': {
      id: '/lore'
      path: '/lore'
      fullPath: '/lore'
      preLoaderRoute: typeof LoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal': {
      id: '/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof TerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmissions': {
      id: '/transmissions'
      path: '/transmissions'
      fullPath: '/transmissions'
      preLoaderRoute: typeof TransmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transmissions/': {
      id: '/transmissions/'
      path: '/'
      fullPath: '/transmissions/'
      preLoaderRoute: typeof TransmissionsIndexRouteImport
      parentRoute: typeof TransmissionsRoute
    }
    '/transmissions/$id': {
      id: '/transmissions/$id'
      path: '/$id'
      fullPath: '/transmissions/$id'
      preLoaderRoute: typeof TransmissionsIdRouteImport
      parentRoute: typeof TransmissionsRoute
    }
  }
}

interface TransmissionsRouteChildren {
  TransmissionsIdRoute: typeof TransmissionsIdRoute
  TransmissionsIndexRoute: typeof TransmissionsIndexRoute
}

const TransmissionsRouteChildren: TransmissionsRouteChildren = {
  TransmissionsIdRoute: TransmissionsIdRoute,
  TransmissionsIndexRoute: TransmissionsIndexRoute,
}

const TransmissionsRouteWithChildren = TransmissionsRoute._addFileChildren(
  TransmissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  AsciiGalleryRoute: AsciiGalleryRoute,
  CongregationRoute: CongregationRoute,
  JobsRoute: JobsRoute,
  LedgerRoute: LedgerRoute,
  LibraryRoute: LibraryRoute,
  LoreRoute: LoreRoute,
  ProtocolRoute: ProtocolRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StakingRoute: StakingRoute,
  StocksRoute: StocksRoute,
  TerminalRoute: TerminalRoute,
  TransmissionsRoute: TransmissionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
